### ISSUE TITLE
🐛 Search filters with custom paths do not work as expected when multiple paths are provided.

### ISSUE THREAD

**Issue by programming-with-ia** [lin-ycv/EverythingPowerToys#168]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've updated PowerToys (PT), Everything, EverythingPT (EPT) to the lastest version
- [ ] I've tried reinstalling PT, Everything, EPT

**Describe the Bug**  
Search filters with custom paths do not work as expected when multiple paths are provided.  

**Example Configuration**  
```toml
# Search filters using custom paths separated by "|"
demo = C:\Windows\|C:\ProgramData  # Not working
sh = C:\Users\immi\Desktop\Shortcuts  # Working
```

=
**Version:**
 - PowerToy:latest
 - Everything:latest
 - EverythingPT: latest
 - Windows:windows 11 22h2

 **Installation method (How did you install the following softwares):**
 - Everything-I. 4.1.1026.x64-Setup.exe
 - EverythingPT-0.88.0-x64.exe
